name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      
      - name: Installing libs
        run: pip install -r requirements.dev.txt

      - name: Linting
        run: ruff check . --select F401 --select F403 --quiet

  deployment:
    needs: [lint,test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Preparing image
        run: docker build -t ${{ github.event.repository.name }} -f ./Dockerfile .

      - name: Tagging image
        run: docker image tag ${{ github.event.repository.name }} ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest

      - name: Pushing image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest